### ISSUE TITLE
make sysusers work like tmpfiles

### ISSUE THREAD

**Issue by udeved** [artix-linux/opensysusers#7]
Could we make the sysusers work like tmpfiles in terms of reading the files?
Ie, a pacman-hook or init script takes care of the different locations, so we can unify pacman hooks?

**Comment by udeved** [comment]
https://github.com/artix-linux/packages/blob/master/opentmpfiles/trunk/tmpfiles-hook

vs

https://github.com/artix-linux/packages/blob/master/opensysusers/trunk/sysusers-hook

**Comment by cromerc** [comment]
I would prefer not to, I wrote opensysusers with 2 things in mind, one to be distro independent, and the other to be faithful to the way that sysusers.d from systemd works(same arguments, usage, functionality, etc). By doing this change it would be something for just Artix, and it would be adding functionality that systemd does not offer in it's implementation. However if you would like it to work like that, I could write a patch that could be applied in the package rather than in this project directly?

**Comment by udeved** [comment]
Great. I put it in goblins.

Fun fact by namcap.

> 
10:36:36 opensysusers W: Package was 52% docs by size; maybe you should split out a docs package
